// <auto-generated />
using BookApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookApi.Migrations
{
    [DbContext(typeof(BookContext))]
    [Migration("20250715063420_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("BookApi.Models.Book", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .HasColumnType("TEXT");

                    b.Property<string>("Genre")
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .HasColumnType("TEXT");

                    b.Property<int>("PublishedYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Author = "Harper Lee",
                            Genre = "Fiction",
                            Language = "English",
                            PublishedYear = 1960,
                            Title = "To Kill a Mockingbird"
                        },
                        new
                        {
                            ID = 2,
                            Author = "George Orwell",
                            Genre = "Dystopian",
                            Language = "English",
                            PublishedYear = 1949,
                            Title = "1984"
                        },
                        new
                        {
                            ID = 3,
                            Author = "Jane Austen",
                            Genre = "Romance",
                            Language = "English",
                            PublishedYear = 1813,
                            Title = "Pride and Prejudice"
                        },
                        new
                        {
                            ID = 4,
                            Author = "F. Scott Fitzgerald",
                            Genre = "Tragedy",
                            Language = "English",
                            PublishedYear = 1925,
                            Title = "The Great Gatsby"
                        },
                        new
                        {
                            ID = 5,
                            Author = "Herman Melville",
                            Genre = "Adventure",
                            Language = "English",
                            PublishedYear = 1851,
                            Title = "Moby-Dick"
                        },
                        new
                        {
                            ID = 6,
                            Author = "Leo Tolstoy",
                            Genre = "Historical",
                            Language = "Russian",
                            PublishedYear = 1869,
                            Title = "War and Peace"
                        },
                        new
                        {
                            ID = 7,
                            Author = "J.D. Salinger",
                            Genre = "Fiction",
                            Language = "English",
                            PublishedYear = 1951,
                            Title = "The Catcher in the Rye"
                        },
                        new
                        {
                            ID = 8,
                            Author = "J.R.R. Tolkien",
                            Genre = "Fantasy",
                            Language = "English",
                            PublishedYear = 1937,
                            Title = "The Hobbit"
                        },
                        new
                        {
                            ID = 9,
                            Author = "Fyodor Dostoevsky",
                            Genre = "Philosophical",
                            Language = "Russian",
                            PublishedYear = 1866,
                            Title = "Crime and Punishment"
                        },
                        new
                        {
                            ID = 10,
                            Author = "Fyodor Dostoevsky",
                            Genre = "Philosophical",
                            Language = "Russian",
                            PublishedYear = 1880,
                            Title = "The Brothers Karamazov"
                        },
                        new
                        {
                            ID = 11,
                            Author = "Aldous Huxley",
                            Genre = "Dystopian",
                            Language = "English",
                            PublishedYear = 1932,
                            Title = "Brave New World"
                        },
                        new
                        {
                            ID = 12,
                            Author = "J.R.R. Tolkien",
                            Genre = "Fantasy",
                            Language = "English",
                            PublishedYear = 1954,
                            Title = "The Lord of the Rings"
                        },
                        new
                        {
                            ID = 13,
                            Author = "Charlotte Brontë",
                            Genre = "Gothic",
                            Language = "English",
                            PublishedYear = 1847,
                            Title = "Jane Eyre"
                        },
                        new
                        {
                            ID = 14,
                            Author = "Emily Brontë",
                            Genre = "Gothic",
                            Language = "English",
                            PublishedYear = 1847,
                            Title = "Wuthering Heights"
                        },
                        new
                        {
                            ID = 15,
                            Author = "Homer",
                            Genre = "Epic",
                            Language = "Greek",
                            PublishedYear = -800,
                            Title = "The Odyssey"
                        },
                        new
                        {
                            ID = 16,
                            Author = "Dante Alighieri",
                            Genre = "Epic",
                            Language = "Italian",
                            PublishedYear = 1320,
                            Title = "The Divine Comedy"
                        },
                        new
                        {
                            ID = 17,
                            Author = "Miguel de Cervantes",
                            Genre = "Satire",
                            Language = "Spanish",
                            PublishedYear = 1605,
                            Title = "Don Quixote"
                        },
                        new
                        {
                            ID = 18,
                            Author = "Paulo Coelho",
                            Genre = "Quest",
                            Language = "Portuguese",
                            PublishedYear = 1988,
                            Title = "The Alchemist"
                        },
                        new
                        {
                            ID = 19,
                            Author = "Leo Tolstoy",
                            Genre = "Realist",
                            Language = "Russian",
                            PublishedYear = 1877,
                            Title = "Anna Karenina"
                        },
                        new
                        {
                            ID = 20,
                            Author = "John Steinbeck",
                            Genre = "Novel",
                            Language = "English",
                            PublishedYear = 1939,
                            Title = "The Grapes of Wrath"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
